const imageDatabase = [
  { set0: [
    { src: './img/sharing-00-00.jpg' },
    { src: './img/sharing-00-01.jpg' },
    { src: './img/sharing-00-02.jpg' },
    { src: './img/sharing-00-03.jpg' },
    { src: './img/sharing-00-04.jpg' },
  ]},
  { set1: [
    { src: './img/empathy-00-00.jpg' },
    { src: './img/empathy-00-01.jpg' },
    { src: './img/empathy-00-02.jpg' },
    { src: './img/empathy-00-03.jpg' },
    { src: './img/empathy-00-04.jpg' },
  ]},
  { set2: [
    { src: './img/cooperating-00-00.jpg' },
    { src: './img/cooperating-00-01.jpg' },
    { src: './img/cooperating-00-02.jpg' },
    { src: './img/cooperating-00-03.jpg' },
    { src: './img/cooperating-00-04.jpg' },
  ]},
  { set3: [
    { src: './img/helping-00-00.jpg' },
    { src: './img/helping-00-01.jpg' },
    { src: './img/helping-00-02.jpg' },
    { src: './img/helping-00-03.jpg' },
    { src: './img/helping-00-04.jpg' },
  ]},  
  { set4: [
    { src: './img/eating-00-00.jpg' },
    { src: './img/eating-00-01.jpg' },
    { src: './img/eating-00-02.jpg' },
    { src: './img/eating-00-03.jpg' },
    { src: './img/eating-00-04.jpg' },
  ]},  
  { set5: [
    { src: './img/engaging-00-00.jpg' },
    { src: './img/engaging-00-01.jpg' },
    { src: './img/engaging-00-02.jpg' },
    { src: './img/engaging-00-03.jpg' },
    { src: './img/engaging-00-04.jpg' },
  ]},  
  { set6: [
    { src: './img/handshake-00-00.jpg' },
    { src: './img/handshake-00-01.jpg' },
    { src: './img/handshake-00-02.jpg' },
    { src: './img/handshake-00-03.jpg' },
    { src: './img/handshake-00-04.jpg' },
  ]}, 
  { set7: [
    { src: './img/turntaking-00-00.jpg' },
    { src: './img/turntaking-00-01.jpg' },
    { src: './img/turntaking-00-02.jpg' },
    { src: './img/turntaking-00-03.jpg' },
    { src: './img/turntaking-00-04.jpg' },
  ]},
  { set8: [
    { src: './img/sportsmanship-00-00.jpg' },
    { src: './img/sportsmanship-00-01.jpg' },
    { src: './img/sportsmanship-00-02.jpg' },
    { src: './img/sportsmanship-00-03.jpg' },
    { src: './img/sportsmanship-00-04.jpg' },
  ]},
  { set9: [
    { src: './img/animalcare-00-00.jpg' },
    { src: './img/animalcare-00-01.jpg' },
    { src: './img/animalcare-00-02.jpg' },
    { src: './img/animalcare-00-03.jpg' },
    { src: './img/animalcare-00-04.jpg' },
  ]},
  { set10: [
    { src: './img/listeningmusic-00-00.jpg' },
    { src: './img/listeningmusic-00-01.jpg' },
    { src: './img/listeningmusic-00-02.jpg' },
    { src: './img/listeningmusic-00-03.jpg' },
    { src: './img/listeningmusic-00-04.jpg' },
  ]},
  { set11: [
    { src: './img/personalspace-00-00.jpg' },
    { src: './img/personalspace-00-01.jpg' },
    { src: './img/personalspace-00-02.jpg' },
    { src: './img/personalspace-00-03.jpg' },
    { src: './img/personalspace-00-04.jpg' },
  ]},
  { set12: [
    { src: './img/interested-00-00.jpg' },
    { src: './img/interested-00-01.jpg' },
    { src: './img/interested-00-02.jpg' },
    { src: './img/interested-00-03.jpg' },
    { src: './img/interested-00-04.jpg' },
  ]},
  { set13: [
    { src: './img/happy-00-00.jpg' },
    { src: './img/happy-00-01.jpg' },
    { src: './img/happy-00-02.jpg' },
    { src: './img/happy-00-03.jpg' },
    { src: './img/happy-00-04.jpg' },
  ]},
  { set14: [
    { src: './img/teamwork-00-00.jpg' },
    { src: './img/teamwork-00-01.jpg' },
    { src: './img/teamwork-00-02.jpg' },
    { src: './img/teamwork-00-03.jpg' },
    { src: './img/teamwork-00-04.jpg' },
  ]}
];
